#!/usr/bin/env bash
set -e
[ -n "$LUENV_DEBUG" ] && set -x

# Provide luenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec luenv-versions --bare
fi

LUENV_VERSION="$1"
LUENV_VERSION_FILE=".luenv-version"

if [ "$LUENV_VERSION" = "--unset" ]; then
  rm -f "$LUENV_VERSION_FILE"
elif [ -n "$LUENV_VERSION" ]; then
  luenv-version-file-write "$LUENV_VERSION_FILE" "$LUENV_VERSION"
else
  luenv-version-file-read "$LUENV_VERSION_FILE" ||
  { echo "luenv: no local version configured for this directory"
    exit 1
  } >&2
fi
