#!/usr/bin/env bash
set -e
[ -n "$LUENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  echo "usage: luenv completions COMMAND [arg1 arg2...]" >&2
  exit 1
fi

COMMAND_PATH="$(command -v "luenv-$COMMAND" || command -v "luenv-sh-$COMMAND")"
if grep -i "^# provide luenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
