#!/usr/bin/env bash
set -e
[ -n "$LUENV_DEBUG" ] && set -x

# Provide luenv completions
if [ "$1" = "--complete" ]; then
  exec luenv shims --short
fi

LUENV_COMMAND="$1"
if [ -z "$LUENV_COMMAND" ]; then
  echo "usage: luenv exec COMMAND [arg1 arg2...]" >&2
  exit 1
fi

LUENV_COMMAND_PATH="$(luenv-which "$LUENV_COMMAND")"
LUENV_BIN_PATH="${LUENV_COMMAND_PATH%/*}"

for script in $(luenv-hooks exec); do
  source "$script"
done

shift 1
export PATH="${LUENV_BIN_PATH}:${PATH}"
exec -a "$LUENV_COMMAND" "$LUENV_COMMAND_PATH" "$@"
