#!/usr/bin/env bash
set -e
[ -n "$LUENV_DEBUG" ] && set -x

print_set_version() {
  echo "<version> should be a string matching a Lua version known by luenv."

  local versions="$(luenv-versions --bare)"
  if [ -z "$versions" ]; then
    echo "There are currently no Lua versions installed for luenv."
  else
    echo "The currently installed Lua versions are:"
    echo "$versions" | sed 's/^/  /'
  fi

  echo
  echo "The special version string 'system' will use your default system Lua."
}

case "$1" in
"") echo "usage: luenv <command> [<args>]

Some useful luenv commands are:
   commands      List all luenv commands
   rehash        Rehash luenv shims (run this after installing binaries)
   global        Set or show the global Lua version
   local         Set or show the local directory-specific Lua version
   shell         Set or show the shell-specific Lua version
   version       Show the current Lua version
   versions      List all Lua versions known by luenv
   which         Show the full path for the given Lua command
   whence        List all Lua versions with the given command

See 'luenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/azukiapp/luenv#readme"
;;
global) echo "usage: luenv global <version>

Sets the global Lua version. You can override the global version at
any time by setting a directory-specific version with \`luenv local'
or by setting the LUENV_VERSION environment variable.

$(print_set_version)"
;;
local) echo "usage: luenv local <version>
       luenv local --unset

Sets the local directory-specific Lua version by writing the version
name to a file named '.luenv-version'.

When you run a Lua command, luenv will look for an '.luenv-version'
file in the current directory and each parent directory. If no such
file is found in the tree, luenv will use the global Lua version
specified with \`luenv global', or the version specified in the
LUENV_VERSION environment variable.

$(print_set_version)"
;;
shell) echo "usage: luenv shell <version>
       luenv shell --unset

Sets a shell-specific Lua version by setting the 'LUENV_VERSION'
environment variable in your shell. This version overrides both
project-specific versions and the global version.

$(print_set_version)"
;;
which) echo "usage: luenv which <command>

Displays the full path to the binary that luenv will execute when you
run the given command."
;;
whence) echo "usage: luenv whence <command>

Lists all Lua versions with the given command installed."
;;
*)
  command_path="$(command -v "luenv-$1" || true)"
  if [ -n "$command_path" ]; then
    echo "Sorry, the \`$1' command isn't documented yet."
    echo
    echo "You can view the command's source here:"
    echo "$command_path"
    echo
  else
    echo "luenv: no such command \`$1'"
  fi
esac
